I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00keymap.rpy", line 469, in script
    python hide:
  File "renpy/common/00keymap.rpy", line 469, in <module>
    python hide:
  File "renpy/common/00keymap.rpy", line 488, in _execute_python_hide
    renpy.save("_reload-1", "reload save game")
AttributeError: 'NoneType' object has no attribute 'stores'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00keymap.rpy", line 469, in script
    python hide:
  File "/home/nanaseren/Downloads/renpy-7.4.11-sdk/renpy/ast.py", line 943, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/home/nanaseren/Downloads/renpy-7.4.11-sdk/renpy/python.py", line 875, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00keymap.rpy", line 469, in <module>
    python hide:
  File "renpy/common/00keymap.rpy", line 488, in _execute_python_hide
    renpy.save("_reload-1", "reload save game")
  File "/home/nanaseren/Downloads/renpy-7.4.11-sdk/renpy/loadsave.py", line 376, in save
    roots = renpy.game.log.freeze(None)
  File "/home/nanaseren/Downloads/renpy-7.4.11-sdk/renpy/rollback.py", line 980, in freeze
    self.complete(False)
  File "/home/nanaseren/Downloads/renpy-7.4.11-sdk/renpy/rollback.py", line 564, in complete
    self.current.stores[name], self.current.delta_ebc[name] = sd.get_changes(begin)
AttributeError: 'NoneType' object has no attribute 'stores'

Linux-5.13.0-28-generic-x86_64-with-debian-bullseye-sid
Ren'Py 7.5.0.22021101n
featureDemoProject 1.0
Sat Feb 19 00:31:24 2022
